INSERT INTO configuration (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, set_function, date_added) VALUES ('Product Card Layout', 'IS_PRODUCT_PRODUCTS_LAYOUT', 'card-deck', 'What Layout suits your shop?  See https://getbootstrap.com/docs/4.3/components/card/#card-layout <div class="secWarning">card-columns is a special use case that will not suit most shops as card-columns is very difficult to layout and sort by...</div>', '8', '100', 'tep_cfg_select_option(array(\'card-group\', \'card-deck\', \'card-columns\'), ', now());
INSERT INTO configuration (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, set_function, date_added) VALUES ('Products In Each Row (SM)', 'IS_PRODUCT_PRODUCTS_DISPLAY_ROW_SM', '2', 'How many products should display per Row in SM (Small) viewport?', '8', '110', 'tep_cfg_select_option(array(\'12\', \'11\', \'10\', \'9\', \'8\', \'7\', \'6\', \'5\', \'4\', \'3\', \'2\', \'1\'), ', now());
INSERT INTO configuration (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, set_function, date_added) VALUES ('Products In Each Row (MD)', 'IS_PRODUCT_PRODUCTS_DISPLAY_ROW_MD', '3', 'How many products should display per Row in MD (Medium) viewport?', '8', '120', 'tep_cfg_select_option(array(\'12\', \'11\', \'10\', \'9\', \'8\', \'7\', \'6\', \'5\', \'4\', \'3\', \'2\', \'1\'), ', now());
INSERT INTO configuration (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, set_function, date_added) VALUES ('Products In Each Row (LG)', 'IS_PRODUCT_PRODUCTS_DISPLAY_ROW_LG', '4', 'How many products should display per Row in LG (Large) viewport?', '8', '130', 'tep_cfg_select_option(array(\'12\', \'11\', \'10\', \'9\', \'8\', \'7\', \'6\', \'5\', \'4\', \'3\', \'2\', \'1\'), ', now());
INSERT INTO configuration (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, set_function, date_added) VALUES ('Products In Each Row (XL)', 'IS_PRODUCT_PRODUCTS_DISPLAY_ROW_XL', '4', 'How many products should display per Row in XL (Large) viewport?', '8', '140', 'tep_cfg_select_option(array(\'12\', \'11\', \'10\', \'9\', \'8\', \'7\', \'6\', \'5\', \'4\', \'3\', \'2\', \'1\'), ', now());

INSERT INTO configuration (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, date_added) VALUES ('Sort Option: Latest Added (0=disable; 1=enable)', 'PRODUCT_LIST_ID', '1', 'Allow sorting by Latest Added?', '8', '260', now());
INSERT INTO configuration (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, date_added) VALUES ('Sort Option: Sales (0=disable; 1=enable)', 'PRODUCT_LIST_ORDERED', '1', 'Allow sorting by Number of Sales?', '8', '270', now());


UPDATE configuration SET configuration_title = 'Sort Option: Manufacturer Name (0=disable; 1=enable)', configuration_description = 'Allow Sorting By Manufacturer Name?', sort_order = '200' WHERE configuration_key = 'PRODUCT_LIST_MANUFACTURER';
UPDATE configuration SET configuration_title = 'Sort Option: Model (0=disable; 1=enable)', configuration_description = 'Allow Sorting By Product Model?', sort_order = '210' WHERE configuration_key = 'PRODUCT_LIST_MODEL';
UPDATE configuration SET configuration_title = 'Sort Option: Name (0=disable; 1=enable)', configuration_description = 'Allow Sorting By Product Name?', sort_order = '220' WHERE configuration_key = 'PRODUCT_LIST_NAME';
UPDATE configuration SET configuration_title = 'Sort Option: Price (0=disable; 1=enable)', configuration_description = 'Allow Sorting By Product Price?', sort_order = '230' WHERE configuration_key = 'PRODUCT_LIST_PRICE';
UPDATE configuration SET configuration_title = 'Sort Option: Stock (0=disable; 1=enable)', configuration_description = 'Allow Sorting By Product Quantity (Stock)?', sort_order = '240' WHERE configuration_key = 'PRODUCT_LIST_QUANTITY';
UPDATE configuration SET configuration_title = 'Sort Option: Weight (0=disable; 1=enable)', configuration_description = 'Allow Sorting By Product Weight?', sort_order = '250' WHERE configuration_key = 'PRODUCT_LIST_WEIGHT';
UPDATE configuration SET configuration_title = 'Product Image (defunct)', configuration_description = '<div class="secError">This is a defunct setting.</div>', sort_order = '280' WHERE configuration_key = 'PRODUCT_LIST_IMAGE';
UPDATE configuration SET configuration_title = 'Buy Now column (defunct)', configuration_description = '<div class="secError">This is a defunct setting.</div>', sort_order = '290' WHERE configuration_key = 'PRODUCT_LIST_BUY_NOW';
UPDATE configuration SET sort_order = '300' WHERE configuration_key = 'PRODUCT_LIST_FILTER';
UPDATE configuration SET sort_order = '310' WHERE configuration_key = 'PREV_NEXT_BAR_LOCATION';